import Groq from "groq-sdk";

const client = new Groq({
  apiKey: process.env.GROQ_API_KEY,
});

function cleanAiJson(content) {
  return String(content || "")
    .replace(/```json/gi, "")
    .replace(/```/g, "")
    .trim();
}

function parseAiJson(content) {
  const cleaned = cleanAiJson(content);

  if (!cleaned) {
    throw new Error("AI returned an empty response");
  }

  try {
    return JSON.parse(cleaned);
  } catch (error) {
    console.error("Invalid AI JSON:", cleaned);
    throw new Error(`AI returned invalid JSON: ${error.message}`);
  }
}

function normalizeString(value) {
  return typeof value === "string" ? value.trim() : "";
}

function normalizeList(value) {
  if (!Array.isArray(value)) {
    return [];
  }

  return value
    .filter((item) => typeof item === "string")
    .map((item) => item.trim())
    .filter(Boolean);
}

function normalizePriority(value) {
  const priority = normalizeString(value);

  return ["Low", "Medium", "High", "Critical"].includes(priority)
    ? priority
    : "Medium";
}

function normalizeType(value) {
  const type = normalizeString(value);

  return ["Positive", "Negative", "Edge Case", "Regression"].includes(type)
    ? type
    : "Positive";
}

function normalizeSeverity(value) {
  const severity = normalizeString(value);

  return ["Low", "Medium", "High", "Critical"].includes(
    severity
  )
    ? severity
    : "Medium";
}

function normalizeTestCase(testCase, index) {
  return {
    id: `TC-${String(index + 1).padStart(3, "0")}`,

    feature:
      normalizeString(testCase?.feature) || "",

    title:
      normalizeString(testCase?.title) ||
      `Test Case ${index + 1}`,

    description:
      normalizeString(testCase?.description) || "",

    type: normalizeType(testCase?.type),

    severity:
      normalizeSeverity(testCase?.severity),

    priority:
      normalizePriority(testCase?.priority),

    status: "",

    preconditions:
      normalizeList(testCase?.preconditions),

    steps:
      normalizeList(testCase?.steps),

    expectedResult:
      normalizeString(testCase?.expectedResult),
  };
}

function normalizeResponse(data) {
  const testCases = Array.isArray(data?.testCases)
    ? data.testCases
    : [];

  return {
    testCases: testCases.map(normalizeTestCase),
  };
}

function selectedTypes(testTypes) {
  const types = [];

  if (testTypes?.positive) types.push("Positive");
  if (testTypes?.negative) types.push("Negative");
  if (testTypes?.edge) types.push("Edge Case");
  if (testTypes?.regression) types.push("Regression");

  return types;
}

export async function generateRequirementTestCases(input) {
  const { context, testTypes } = input;

  const types = selectedTypes(testTypes);

  if (!types.length) {
    const error = new Error("At least one test case type must be selected");
    error.statusCode = 400;
    throw error;
  }

  try {
    const prompt = `
You are a Senior QA Engineer specializing in professional manual test design.

Generate executable test cases based strictly on the provided test context.

Selected test case types:
${types.join(", ")}

IMPORTANT OUTPUT RULES:

- Return valid JSON only.
- Return exactly one JSON object.
- Do not use markdown.
- Do not use code fences.
- Do not include comments.
- Do not include text before or after the JSON.
- Keep the response concise.
- Generate a maximum of 12 test cases total.
- Prefer quality and coverage over quantity.
- Use no more than 6 execution steps per test case.
- Keep each step concise.
- Keep preconditions concise.

TEST DESIGN RULES:

- Generate only selected test case types.
- Avoid duplicate scenarios.
- Test cases must be independently executable where practical.
- Steps must be specific and executable.
- Expected results must be observable and testable.
- Never use vague expected results such as "works correctly".
- Do not present unsupported assumptions as confirmed requirements.
- Edge Case tests should focus on boundaries and unusual conditions.
- Regression tests should cover existing functionality reasonably affected by the feature.
- Priority should represent testing importance and product impact.
- Feature should contain a short name for the functionality being tested.
- Description should briefly explain the purpose or scenario of the test case.
- Severity represents the impact if the tested functionality fails.
- Status must not be generated by AI because execution status is determined by the QA Engineer.

Allowed priority values:
- Low
- Medium
- High
- Critical

Allowed severity values:
- Low
- Medium
- High
- Critical

Allowed types:
"Positive"
"Negative"
"Edge Case"
"Regression"

Allowed priorities:
"Low"
"Medium"
"High"
"Critical"

Required JSON structure:

{
  "testCases": [
    {
      "feature": "User Authentication",
      "title": "Verify login with valid credentials",
      "description": "Verify that a registered user can successfully authenticate using valid credentials.",
      "type": "Positive",
      "severity": "High",
      "priority": "High",
      "preconditions": [
        "User has a registered and active account"
      ],
      "steps": [
        "Navigate to the login page",
        "Enter a valid email address",
        "Enter the correct password",
        "Click the Login button"
      ],
      "expectedResult": "User is authenticated and redirected to the expected page."
    }
  ]
}

Test Context:
${context}
`;

    const completion = await client.chat.completions.create({
      model: "openai/gpt-oss-20b",

      messages: [
        {
          role: "system",
          content:
            "You are a Senior QA Engineer. Return valid JSON only and follow the requested schema exactly.",
        },
        {
          role: "user",
          content: prompt,
        },
      ],

      temperature: 0.1,

      max_completion_tokens: 6000,

      response_format: {
        type: "json_object",
      },
    });

    const choice = completion.choices?.[0];

    const content = choice?.message?.content;

    if (!content) {
      throw new Error("AI returned an empty response");
    }

    if (choice?.finish_reason === "length") {
      throw new Error(
        "AI response exceeded the maximum output length"
      );
    }

    const parsed = parseAiJson(content);

    const normalized = normalizeResponse(parsed);

    if (!normalized.testCases.length) {
      throw new Error("AI returned no valid test cases");
    }

    return normalized;
  } catch (error) {
    console.error(
      "Requirement test case generation failed:",
      error
    );

    if (error.statusCode === 400) {
      throw error;
    }

    const serviceError = new Error(
      "Test case generation failed"
    );

    serviceError.statusCode = 500;

    throw serviceError;
  }
}